server {
  listen 80;

  location / {
    root /usr/share/nginx/html;
    index index.html;
    # This makes React Router work — always serve index.html
    try_files $uri $uri/ /index.html;
  }

  # Forward all /auth, /projects, /tasks, /users API calls to backend
  location ~ ^/(auth|projects|tasks|users) {
    proxy_pass http://backend:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}